language: c

compiler:
  - gcc

before_script:
  - ./bootstrap
  - ./configure
  - make
  - cpanm --quiet --notest Test::More IPC::Run3

script:
  - make check

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
