language: c

compiler:
  - clang
  - gcc

before_script:
  - ./bootstrap
  - CFLAGS="-std=c99 -Wall -Wextra -Werror -Wno-unused-parameter" ./configure
  - make

script:
  - make check

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
