install:
  - git submodule update --init --recursive

test_script:
  - forfiles /p .\projects\VS12\Debug\ /m *.exe /c "cmd /c cd ..\..\.. && @PATH"

notifications:
  - provider: HipChat
    auth_token:
      secure: NtKXu/kGk8Td4YqCH95camAcNQtB3rMll+5DALAmbDY=
    room: dev
